remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: dx-junkyard
description: 様々なハッカソンに参加する全国チーム
show_downloads: false
github:
  url: https://github.com/dx-junkyard
lang: ja
